### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by androidacy-user** [AndreaCioccarelli/MusicDownloader#4]
Download won't start with main/error or video length exceeds 3 hours(for a 4 minute video) 

_Sent from my TETRA using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by cioccarellia** [comment]
Which video are you talking about? Could you provide a more detailed report?



_Sent from my OnePlus5 using [Real FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by androidacy-user** [comment]
It's not one. It's every one. I gave exact error messages. 


_Sent from my TETRA using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by cioccarellia** [comment]
Try updating to the latest version, for me it works
