### ISSUE TITLE
Apps crashing in first launch after install

### ISSUE THREAD

**Issue by masudr4n4** [AndreaCioccarelli/MusicDownloader#8]
<h4>Actual behavior</h4>
Occuring error  in first launch after installation.
<h4>Expected behavior</h4>
I expected that i can launch the app without any error after installation.
<h4>How to reproduce</h4>
<ol>
<li>Download the app from releas page</li>
<li>you must close data connection to see the error</li>
<li>click the appp to install</li>
<li>click install</li>
<li>wait for appear open option then click open.</li>
<li>See error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v1.3.5</li>
<li>OS:Android 6.0.1</li>
<li>Device:Samsung J5</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/lK3U1WwaRYI">https://youtu.be/lK3U1WwaRYI</a>
<h4>Logcat</h4>
<pre>
<code>
04-14 10:48:55.845 12242 12298 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2

04-14 10:48:55.845 12242 12298 E AndroidRuntime: Process: com.andreacioccarelli.musicdownloader, PID: 12242

04-14 10:48:55.885  3590 11935 D ResourcesManager: For user 0 new overlays fetched Null

04-14 10:48:55.885  1650 12302 E android.os.Debug: ro.product_ship = true

04-14 10:48:55.885  1650 12302 E android.os.Debug: ro.debug_level = 0x4f4c

04-14 10:48:55.885  1650 12302 E android.os.Debug: sys.mobilecare.preload = false

04-14 10:48:55.885 12242 12242 D TextView: setTypeface with style : 0

04-14 10:48:55.885 12242 12242 I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.

04-14 10:48:55.915 12242 12242 D TextView: setTypeface with style : 0

04-14 10:48:55.925  1650 12301 W DropBoxManagerService: Dropping: data_app_crash (3097 > 0 bytes)

04-14 10:48:55.945  1650  1836 D ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{377e3ac V.E...... R.....I. 0,0-0,0}

04-14 10:48:55.955 12242 12242 W ClipboardManager: not support ClipboardEx

04-14 10:48:55.955  1650  1674 D SecContentProvider: query(), uri = 15 selection = isClipboardAllowedAsUser

04-14 10:48:55.955  1650  1836 V MARsPolicyManager: handelAlertToastWindowStarted pkgName = android

04-14 10:48:55.955  1650  1836 D InputDispatcher: Focus entered window: 1650

04-14 10:48:55.955  1650  1674 D SecContentProvider: query(), uri = 15 selection = isClipboardShareAllowedAsUser

04-14 10:48:55.955  1650  1930 D PointerIcon: setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:1650 uid:1000

04-14 10:48:55.955  1650  1930 D PointerIcon: setMouseCustomIcon IconType is same.101

04-14 10:48:55.955  1650  1674 D SecContentProvider: query(), uri = 15 selection = isClipboardShareAllowedAsUser

04-14 10:48:55.965  1650  1674 D SecContentProvider: query(), uri = 15 selection = isClipboardShareAllowedAsUser

04-14 10:48:55.965   341   341 I SurfaceFlinger: id=794 createSurf (97x97),1 flag=4, nusicdownlo

04-14 10:48:55.975  1650  2356 I OpenGLRenderer: Initialized EGL, version 1.4

04-14 10:48:55.995  1650  1664 I art     : Background sticky concurrent mark sweep GC freed 79531(14MB) AllocSpace objects, 1(20KB) LOS objects, 29% free, 35MB/50MB, paused 9.542ms total 136.639ms

04-14 10:48:55.995  1650  1836 D ScrollView:  onsize change changed 

04-14 10:48:55.995  1650  1836 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{9d5f00a u0 d0 p1650 Application Error: com.andreacioccarelli.musicdownloader}
</code>
</pre>

**Comment by cioccarellia** [comment]
Really weird. I would have bet that the online/offline switch was working perfectly, but I could reproduce this issue. Thanks for this catch! Going to dig it around

**Comment by masudr4n4** [comment]
welcome and hoping you will fix that soon.

**Comment by cioccarellia** [comment]
A full fix is scheduled by tomorrow :)

**Comment by masudr4n4** [comment]
Tnx

**Comment by cioccarellia** [comment]
Fixed in 1.3.8, it was an Exception raised by the update checker module.

**Comment by masudr4n4** [comment]
dear @AndreaCioccarelli can you add apk file in the release page? i don't see you added the apk file.or can you upload your apk to f-droid or other plateform and cite the url in the readme page.tnx

**Comment by cioccarellia** [comment]
You can find it in the `bin` folder of the repo
